### ISSUE TITLE
Användare i historiken sparas fel

### ISSUE THREAD

**Issue by torandi** [datasektionen/cashflow-old#17]
Användaren i ett inköps historik verkar helt borkat. Om person A skapar ett verifikat och B sen godkänner och betalar ut så kommer det stå A på alla historiksposter.
Om C sen ändrar något i inköpet ändras hela historiken till C...

**Comment by Frost** [comment]
Jo, jag vet. Jag försökte fixa det igår, men det är lite svårtestat.

**Comment by Frost** [comment]
Det ser ut att vara fixat nu. De sparades inte fel btw, utan de lästes bara upp fel.
