### ISSUE TITLE
extrahera budgetposttabellen till en partial

### ISSUE THREAD

**Issue by Frost** [datasektionen/cashflow-old#18]
https://github.com/datasektionen/cashflow/blob/8c0fbd5e29880e21debb3e0538e4a47c245b3ac0/app/views/budget_posts/index.html.haml#L16-46 

```
<spatrik > rad 16 är också lite wtf                     
<@Frost > oj, den hade jag  missat                        
<@Frost > jag har inte rört den där koden, kan jag ju säga               
<@Frost > spatrik: du ser att block används på raderna 43 och 46 sen va?
<@Frost > varför inte bara lägga det i en partial liksom?               
<spatrik > mm                                                             
<spatrik > fast det är ju på sätt och vis en ganska snygg lösning
<spatrik > om det har varit ruby hade det ju varit snyggt                 
<@Frost > precis, men nu är det rails, så det borde vara en partial      
<spatrik > mjo
```

**Comment by torandi** [comment]
Jaja, jag skyller på att jag var trött. Mottagning

**Comment by torandi** [comment]
Men va fan. Comment and close är lite för lätt att klicka på

**Comment by Frost** [comment]
Det är ju det va? Jag tror det är ett tecken på att du borde lägga tre minuter på att fixa detta ;p

**Comment by torandi** [comment]
Jag ska jag ska. Men det är inte som att jag har massa tid över. Och den tid jag har över vill jag lägga på att fixa features i mage för att underlätta livet för oss.

**Comment by Frost** [comment]
Alltså... tre minuter, seriously ;p

**Comment by Frost** [comment]
Den här är förlegad nu. Jag stänger den.
