### ISSUE TITLE
progressbar/diagram för budgetposter

### ISSUE THREAD

**Issue by Frost** [datasektionen/cashflow-old#19]
Vore det inte lite coolt om man kunde se hur stor andel av en budgetpost som är "förbrukad", dels om man går in på `budget_posts#index` och `#show`?

**Comment by torandi** [comment]
Menar du i procent? I dagsläget går det ju att se en översikt över hur mycket som är förbrukat här: http://cashflow.datasektionen.se/budget_posts. Dessutom ser man det på alla inköp som är kopplade till den budgetposten

**Comment by Frost** [comment]
Wall of text menar du? Jag har lite svårt att tyda ut något vettigt ur en wall of text för att få någon form av översikt. Tänk diagram, typ som i listan på ansökningar i STÖn.

**Comment by Frost** [comment]
Sen antar jag att det kanske vore intressant att se huruvida en post ligger över eller under budget, kanske med hjälp av färgkodning på ett eller annat sätt.

Lite intressant att rätt många poster inte har någon budget alls btw ;p

**Comment by torandi** [comment]
Jo, det är inte inlagda, tanken var att lägga in dem en efter som som emma godkände budgetar, men det rann ut i sanden efter ett tag. Tyvärr så är det tveksamt om det här gör så mycket nytta i mottagningen, mycket av budgetarna har stora delar som handlas på mo ändå

**Comment by Frost** [comment]
jo, det brukar ju bli lite så med mottagningen...

**Comment by Frost** [comment]
Detta är fixat iom twitter-bootstrap. Tack @luuse !
