### ISSUE TITLE
Create a usable UI

### ISSUE THREAD

**Issue by Frost** [datasektionen/cashflow-old#2]
The current UI was designed by me, and I've come to think that the app looks better (and is more usable) if you turn stylesheets off...

**Comment by vonbirdie** [comment]
I'm fairly tempted to take a few hours to [Bootstrap](http://twitter.github.com/bootstrap/) it during the weekend.

**Comment by Frost** [comment]
Do that if you wish, but I'm not sure as to how that would help making the UI usable. It would just make the layout depend on another framework...

**Comment by vonbirdie** [comment]
Stor subjektiv issue som är svår att agera på. Close?

**Comment by Frost** [comment]
Ja.
