### ISSUE TITLE
Ny budgetpost saknar fält

### ISSUE THREAD

**Issue by maxnordlund** [datasektionen/cashflow-old#24]
När man ska skapa en ny budgetpost saknas det två fält, som man kan komma åt om man redigerar budgetposten efter det att den är skapad.

Dessutom måste man välja 2012 i budgetår, spar och öppna, innan man kan redigera både 2012 och 2011.

**Comment by Frost** [comment]
Det där är inte helt sant, för det är nämligen så att årtalet inte ligger i budgetpost-modellen, utan i modellen för budgetrader. Anledningen till att det fanns (ja, notera dåtid) två extra fält när man redigerade en budgetpost var för att @torandi försökte luras lite.med er som faktiskt skulle använda det.

Vad jag misstänker att du faktiskt egentligen är ute efter är funktionalitet för att lägga in nästa års budget i cashflow. Stämmer det, föreslår jag att du skriver en feature request om det.

Jag stänger denna.
