### ISSUE TITLE
Kan inte se 2012:s budget

### ISSUE THREAD

**Issue by maxnordlund** [datasektionen/cashflow-old#25]
Trots att det finns en selectbox för att välja budgetår kan man inte välja något annat än 2011.

**Comment by Frost** [comment]
Det är för att cashflow egentligen inte är tänkt som en budgetapplikation, utan egentligen bara en kvittoregistreringsapplikation. Budgetbitarna är halvdant påklistrade i efterhand, strax innan Torandi kom fram till att han skulle bygga MAGE istället.

Selectboxen för budgetår gör att man kan välja godtyckligt budgetår för vilket det finns några inköp (i nuläget), vilket än så länge bara är 2011.

**Comment by Frost** [comment]
```
BudgetController# (ActionView::Template::Error) "undefined method `name' for nil:NilClass"

/var/rails/cashflow/production/current/app/views/budget/show.html.haml:23:in

...jättelångt stacktrace som bara listar gems och inte säger något vettigt.
```

**Comment by Frost** [comment]
Någon (jag gissar @torandi eller @Koronen) fixade detta för ett tag sedan.
