### ISSUE TITLE
Affärsenheter

### ISSUE THREAD

**Issue by maxnordlund** [datasektionen/cashflow-old#26]
Det går inte att lägga till nya affärsenheter (eller så gör jag något fel som den inte berättar...)

Indata.
Redaqtionen
red
Datas alldeles egen tidnings redaqtion.

Utdata:
We're sorry, but something went wrong.

We've been notified about this issue and we'll take a look at it shortly.

**Comment by Frost** [comment]
Jag kan verifiera detta, och även meddela att det kommer vara fixat när vi deployar förändringarna till budget-bitarna, vilket bör ske senast imorgon. Dvs, kodmässigt är detta fixat. Jag stänger denna.
