### ISSUE TITLE
Not null utan standardvärde i migrations

### ISSUE THREAD

**Issue by vonbirdie** [datasektionen/cashflow-old#29]
I db/migrate/20110809094208_create_budget.rb läggs det till en kolumn i purchases tabellen och sätter att den ska ha ett not null värde men det definieras aldrig ett standard värde vilket gör att migrationen dör.

**Comment by Frost** [comment]
Vi borde se över vad våra migrations faktiskt gör, och sen fixa så att de faktiskt fungerar att köra.

Alternativet är att be folk använda `rake db:schema:load` istället.

**Comment by Koronen** [comment]
Jag slänger in #30 här också. Det är ju samma problem, bara en annan migration.

> I https://github.com/datasektionen/cashflow/blob/master/db/migrate/20110809095931_add_year_to_purchase.rb sätts inte ett standardvärde direkt när kolumnen läggs till men den gör det direkt efter.

**Comment by Frost** [comment]
Jag funderar på om man kanske ska köra över best practices och ändra i de ursprungliga migrationerna så att saker funkar som de ska rakt av. Input på det?

**Comment by Koronen** [comment]
Sure. Det vore ju trevligt om man kan köra alla migrations från scratch.
