### ISSUE TITLE
Bryt ut budgeten

### ISSUE THREAD

**Issue by maxnordlund** [datasektionen/cashflow-old#31]
Jag har en känsla av att bryta ut hela budget delen vore bra, inte bara för **cashflow**, utan också för **mage**.

Det är kanske inte rätt forum för något sådant, men jag vet inte riktigt var jag ska lägga denna. (I alla fal tills vi har _teambox_)
Lite grovt tänker jag mig följande:
- Alla ska kunna se budgeten, i framtiden kanske begränsat till sektionsmedlemmar/ths medlemmar.
- Möjlighet att redigera budgeten, men endast nuvarande verksamhetsår (eller åtminstone varna om man försöker ändra längre bak i tiden).
- Möjlighet att skapa en ny budget för nästa verksamhetsmål, blank eller ifylld med data från förra året.
- Rättighetsbegränsningar, standard roller. (när dAuth kommer vore det ju praktiskt om denna lätt kan byta, kan också användas som test till dAuth innan vi byter ut resten).

I en framtiden vore det också bra om man hade möjlighet till detalj/översiktsbudget. Typ DKM och Mottagningen har egna budgetar, vars delsummor och rubriker automatiskt inkluderas i den stora budgeten. Då får vi endast 2 sidor budget, men med möjlighet att kolla på detaljerna i bilagor.

**Comment by Frost** [comment]
1. Vi har teambox.
2. Grym ide, men den borde bo någon annan stans (teambox, skriv in den där), och vi borde sätta oss ner och diskutera detta mer i detalj.

**Comment by Koronen** [comment]
Jag håller med föregående talare. Jag stänger denna och hänvisar vidare diskussion till Teambox.
