### ISSUE TITLE
BudgetPost#destroy borde inte hända.

### ISSUE THREAD

**Issue by Frost** [datasektionen/cashflow-old#33]
Om man försöker ta bort en budgetpost borde cashflow vägra göra detta om någon av de relaterade budgetraderna har några inköp. 

Är så inte fallet, borde den dessutom ta bort alla sina budgetrader.

I nuläget tar den inte bort budgetraderna, vilket gör så att /budget sprängs.

**Comment by PatrikStenmark** [comment]
Och det borde ligga constraints på det på databasnivå! :)

On Friday, November 4, 2011, Martin Frost <
reply@reply.github.com>
wrote:

**Comment by Frost** [comment]
Ja, det ocks. Jag brjar med :dependent => :restrict.

-- Sent from my Palm Pre

---

On 4 Nov 2011 17.04, Patrik Stenmark reply@reply.github.com wrote:

Och det borde ligga constraints p det p databasniv! :)

On Friday, November 4, 2011, Martin Frost <
reply@reply.github.com>
wrote:

> Om man frsker ta bort en budgetpost borde cashflow vgra gra detta om
> ngon av de relaterade budgetraderna har ngra inkp.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/datasektionen/cashflow/issues/33

---

**Comment by vonbirdie** [comment]
Jag är inte helt glad åt hur vilka krav vi ställer på att ett inköp måste ha en budgetpost. Det bör ju alltid finnas en budgetpost för alla inköp som görs men i verkligheten lär det finnas vissa köp som faktiskt inte har en?

**Comment by Frost** [comment]
@luuse Det har inte med detta att göra. Den här issuen handlar om att det gick att ta bort budgetposter vilket sprängde hela budget-vyn. 

Jag håller däremot med dig om att det är lite konstigt. Hela budgetbiten i cashflow är konstig och känns påklistrad i efterhand (villket den är), men vill du ha den där diskussionen föreslår jag att du öppnar en annan issue för det, eller tar det på teambox.

**Comment by Frost** [comment]
Det går åtminstone inte att i UI:t ta bort budgetposter som det ligger inköp på nu. Jag stänger denna.
