### ISSUE TITLE
periodiska mailutskick

### ISSUE THREAD

**Issue by Frost** [datasektionen/cashflow-old#4]
Max kommenterade  om att det kanske vore bra om det bara skickades ut mail från cashflow en gång i veckan med en sammanfattning över vad som hänt, eller något åt det hållet.

Detta istället för att kassören ska få ett mail för varje enskild sak som händer.

Jag undrar om det inte egentligen vore bättre att skicka ett mail någon gång på natten efter varje dag det faktiskt hänt något. Jag tror inte det blir så många mail större delen av året, och under mottagningen skulle ekonomeriet få en liten påminnelse om att pilla cashflow oftare.

Dvs skicka digests dagligen istället för ett mail varje gång något händer.

**Comment by Koronen** [comment]
Jag tycker inte att detta behövs. Kan jag stänga denna?

**Comment by Frost** [comment]
Inte om jag hinner först.
