### ISSUE TITLE
Sidan "Bekräftade inköp" listar för många ärenden

### ISSUE THREAD

**Issue by Koronen** [datasektionen/cashflow-old#41]
Sidan visar redan utbetalda och bokförda inköp. Det borde den inte göra.

Relevanta kodavsnitt är:
- app/controllers/purchases_controller.rb:93
  
  ```
  @purchases = Purchase.confirmed
  ```
- app/models/purchase.rb:28
  
  ```
  scope :confirmed , where(:workflow_state => %w[confirmed bookkept paid finalized])
  ```

**Comment by vonbirdie** [comment]
Jag tycker vi kan ta bort denna sida. Jag har tänkt mig att man kan filtrera mellan de olika statusen direkt på /purchases/ men är inte gjort än. Close + new issue (feature)?

**Comment by Frost** [comment]
Jag har varit inne på det tidigare också, @luuse, men de (dvs @Koronen och @torandi ) bad explicit om just den här sidan. Jag fixar detta så länge, och sen kan vi kolla alternativa lösningar senare
