### ISSUE TITLE
Annan person än en själv i purchase#new?

### ISSUE THREAD

**Issue by vonbirdie** [datasektionen/cashflow-old#44]
Borde man verkligen kunna sätta något annat än en själv som köpt något i purchase#new?

**Comment by Frost** [comment]
ping @torandi, @Koronen. Det är tydligen något som händer, att folk stoppar in kvitton i pärmen men inte kan/orkar fixa med cashflow.

**Comment by Koronen** [comment]
Det Frost beskriver händer hyfsat ofta och vi (admins/kassör) behöver ha stöd för att manuellt lägga in kvitton åt folk, ja.

**Comment by vonbirdie** [comment]
Ok, för admin kan jag möjligtvis förstå det. Men om vi implementerar att man skriver ut från cashflow direkt så man måste redovisa där för att få ut ett papper borde det problemet försvinna?

**Comment by Koronen** [comment]
Ja, det borde lösa problemet. Jag vill dock fortfarande ha kvar möjligheten att manuellt registrera inköp.

**Comment by Frost** [comment]
Menar ni att folk måste skriva in saker på cashflow och skriva ut ett papper för att sätta in det i pärmen själva, eller har jag feltolkat det hela? Jag tycker det känns som ni skulle göra det jobbigare för de flesta. Det är ganska mycket jobbigare att ta sig till en skrivare än att bara fylla i ett papper som redan sitter i pärmen och sen skriva in stuff i cashflow.

**Comment by vonbirdie** [comment]
Stänger denna. Känns som att det var rätt klart.
