### ISSUE TITLE
Endast viktigaste kolumnerna i purchase#index

### ISSUE THREAD

**Issue by vonbirdie** [datasektionen/cashflow-old#46]
Det är väldigt ihoptryckt på mindre skärmar och det är väldigt svårt att få en överblick av vad det är för något. Jag tycker det räcker med dessa kolumner:
- ID
- Beskrivning
- Köpt av
- Status

Redigera länken tycker jag vi kan ta bort också.

**Comment by Frost** [comment]
Är bootstrap så smart att man kan dölja vissa kolumner för vissa skärmupplösningar? Det vore ju annars en lösning. 

Jag håller med dig om att mycket av informationen inte är strikt nödvändig, men det kan vara lite fint att kunna se när saker är inköpta också, exempelvis.

**Comment by vonbirdie** [comment]
Tror inte det går med bootstrap. Det skulle kunna gå med lite smarta media queries och data- attribut. Men det blir fortfarande kladdigt på större skärmar. @Koronen, @torandi vilka kolumner vill ni ha?

**Comment by Koronen** [comment]
IDt i sig är egentligen inte intressant, men är bra att ha där eftersom att det går att söka på det. Detta i brist på ett annat sätt att snabbt accessa ett inköp givet enbart ett ID. Jag skulle även vilja lägga till kolumnen "Inköpt" (datum).
