### ISSUE TITLE
Filtrera efter status i purchase#index

### ISSUE THREAD

**Issue by vonbirdie** [datasektionen/cashflow-old#47]
Vore trevligt. Tänk en twitter nav list på vänster sida som man kan markera de statusar man vill ha med som sedan uppdaterar tabellen dynamiskt med de statusar som berörs.

http://twitter.github.com/bootstrap/components.html

**Comment by Frost** [comment]
#58 löste detta med en button-group istället. Kanske vore det en snyggare lösning med en nav-list, som vi har på budget-sidan. Vad tror folk om det?

**Comment by vonbirdie** [comment]
Jag tror det blir utmärkt med en button group. En nav-list såg inte helt bra ut (jag hade redan en prototyp) så jag tycker det blev bättre nu.

**Comment by Frost** [comment]
Dåså. Då stänger jag denna.
