### ISSUE TITLE
Lista i första hand bara aktiva inköp/skulder

### ISSUE THREAD

**Issue by Frost** [datasektionen/cashflow-old#5]
Det kanske kan vara vettigt att bara visa de inköp/skulder som faktiskt är aktiva (icke avslutade) på "min sida".

Det blir lite konstigt med totalsumman annars, i och med att den bara tar hänsyn till aktiva inköp/skulder.

**Comment by Frost** [comment]
Behövs denna verkligen om vi nu fixar #59?

**Comment by Koronen** [comment]
Ja, för på "min sida" finns i dagsläget ingen filtrering och #59 behandlar (som jag tolkar det, även om det inte står uttryckligen) `Purchase#index`.

**Comment by Frost** [comment]
Ah, right. Det kan ju kanske vara bra om jag läser ordentligt vad jag själv har skrivit också.
