### ISSUE TITLE
behöver vi sass längre?

### ISSUE THREAD

**Issue by Frost** [datasektionen/cashflow-old#52]
Iom att vi gick över till bootstrap, som ju använder less, behöver vi fortfarande ha sass i Gemfile. Har @luuse ett svar på det, kanske?

**Comment by vonbirdie** [comment]
Nej det ska inte behövas längre. Det kan vi ta bort.

**Comment by Frost** [comment]
Varsågod, du fick precis en oneliner-uppgift :)
