### ISSUE TITLE
progressbar för firefox

### ISSUE THREAD

**Issue by Frost** [datasektionen/cashflow-old#53]
Lägg till stylesheet-stuff för att få progressbars att funka i firefox också.

**Comment by vonbirdie** [comment]
Jag skjuter på denna för är inte helt säker på om det går att fixa allt i firefox. Jämför [denna](http://luuse.github.com/experiments/progress_styling.html) sida i Aurora 12 vs. Chrome 19.

**Comment by Frost** [comment]
Jag trodde det bara borde vara att lägga in -moz-prefix i denna: https://github.com/datasektionen/cashflow/blob/master/app/assets/stylesheets/screen.css

Är det svårare än så?

**Comment by vonbirdie** [comment]
Jag testade det men verkar som att mozilla inte har implementerat alla prefix än. Delar av det fungerade men inte allt. Det såg inte dåligt ut utan det heller så jag tycker vi kan vänta?

**Comment by Frost** [comment]
Absolut, vi kan vänta.

**Comment by Frost** [comment]
Detta verkar inte hända... Jag stänger denna tills vidare. Om någon känner för att fixa detta är det bara att köra på.
