### ISSUE TITLE
Filtrera inköp efter flera statusar

### ISSUE THREAD

**Issue by Koronen** [datasektionen/cashflow-old#59]
Se #58.

> luuse: Det kan väl vara trevligt att kunna markera flera (checkbox) state också?
> Frost: Ja, gissningsvis.

Det vore trevligt att kunna markera flera statusar att filtrera på, t.ex. alla nya eller ändrade inköp.

**Comment by Frost** [comment]
Detta är fixat sedan i torsdags.
