### ISSUE TITLE
translation missing: sv.notice.purchase.success.created

### ISSUE THREAD

**Issue by torandi** [datasektionen/cashflow-old#60]
translation missing: sv.notice.purchase.success.created

**Comment by Frost** [comment]
Nu ljuger du. 

Den finns visst, nämligen här: https://github.com/datasektionen/cashflow/blob/master/config/locales/sv.yml#L445.

Det vore dock intressant att veta varför du får det där felet.

**Comment by Koronen** [comment]
Fixat i eea7e0b1e6be983402e90377cd621a7eea04d718.

**Comment by Frost** [comment]
Oh.... sneaky.
