### ISSUE TITLE
Multi-actions för inköp

### ISSUE THREAD

**Issue by Koronen** [datasektionen/cashflow-old#64]
Det vore trevligt att kunna markera flera inköp och utföra en action, t.ex. bekräfta.

**Comment by Koronen** [comment]
Tanken är alltså att man i t.ex. `Purchase#index` har checkboxes vid varje inköp där man väljer vilka inköp som ska beröras. Man ska därefter kunna klicka på en av flera knappar; "Bekräfta alla", "Markera alla som betalda", "Bokför alla" etc. Given action ska då utföras på markerade inköp.

**Comment by Frost** [comment]
Jag tror lite att @luuse ville att såna mer administrativa saker borde göras under "Administration"-fliken i menyn, och på ett sätt förstår jag honom. Vyerna blir bra mycket mindre geggiga på det sättet.

**Comment by vonbirdie** [comment]
Jag har lite tankar på hur man kan automatisera lite saker. Att kunna markera flera inköp och godkänna dem i Purchase#index tycker jag låter väldigt farligt eftersom det blir enkelt att vara lat och inte kolla vad det är för inköp så noga.

Jag skulle gärna se att vi stänger detta issue och pratar lite mer om vilka problem ni har (grundorsaken till varför du vill ha dessa funktioner) och försöker lösa dem på andra sätt.

**Comment by torandi** [comment]
Det primära användningsområdet för detta skulle jag säga är att batch-bokföra inköp mot mage.

**Comment by Frost** [comment]
I så fall tycker jag verkligen att funktionaliteten borde ligga någon annanstans än på `purchases#index`. 

I övrigt fungerar det väl alldeles utmärkt att prata om det här, @luuse? Vi skulle väl förmodligen komma  fram till något vettigare snabbare om vi faktiskt sågs, men det har varit lite kass uppslutning de senaste torsdagarna, kan jag ju säga.

**Comment by vonbirdie** [comment]
När i ett inköps stadie ska sakerna bokföras? Behövs det någon input när man gör det eller är det bara att markera och klicka bokför?

**Comment by vonbirdie** [comment]
Vi kan absolut prata om det här men det är ingen actionable item så det är ingen mening med att den är öppen :).

**Comment by torandi** [comment]
[Bokföra] Det behövs ingen input (vi bestämde oss för att skala bort den ev. lilla input man kan vilja göra i undantagsfall). Om man kör purchase.keep! så markeras ett inköp som bokfört och sen skickas det till mage automagiskt. Det som behöver göras för att "multibokföra" är helt enkelt att iterera över en lämplig mängd inköp och köra keep! på dem.

**Comment by Frost** [comment]
Det som med andra ord behövs är en vy där man kan markera ett flertal inköp och sen markera dem som bokförda. En slags batch-hantering av inköp helt enkelt.

Det borde göras med en separat action (eller kanske till och med en egen controller) som bara är åtkomlig för ekonomiansvariga/admin.

**Comment by Frost** [comment]
Det finns sedan ett bra tag tillbaka en purchases/confirmed, som däremot har funkat lite halvtaskigt. Jag lade nyss upp en pull request som fixar bakomliggande kod och snyggar upp utseendet på vyn.
