### ISSUE TITLE
Ta bort inköpsdelar tycks inte funka

### ISSUE THREAD

**Issue by torandi** [datasektionen/cashflow-old#68]
# Gör detta:
- Skapa inköp med en inköpsdel
- Redigera inköpet
  *\* Ta bort ursprunglig inköpsdel
  *\* Lägg till nya inköpsdelar
# Vad som händer:
- Alla inköpsdelar visas (även den jag tog bort)
# Vad jag väntade mig:
- Bara inköpsdelen jag la till ska visas

**Comment by Frost** [comment]
Detta måste ha dykt upp med bootstrap, för jag vet att det funkade innan dess. Känner du för att kolla på detta, @luuse?

**Comment by Frost** [comment]
Ah, nej, jag vet vad det är. Det beror på att vi faktiskt måste iterera över inköpsdelarna och ta bort de som inte postas från `edit`-formuläret.

**Comment by torandi** [comment]
eller använda _destroy?

**Comment by Frost** [comment]
Ja, det är ju också en idé.

**Comment by vonbirdie** [comment]
Jag har tyvärr väldigt mycket som händer just nu så kommer tyvärr inte hinna hålla på så mycket med Cashflow på ett par veckor.
