### ISSUE TITLE
Enormt stora värden trunkeras utan varning

### ISSUE THREAD

**Issue by torandi** [datasektionen/cashflow-old#69]
Inte för att det egentligen ska hända, men matar man in stora summor på inköp trunkeras de utan att man varnas. Man borde istället få en varning om att beloppet är orimligt stort.

**Comment by Frost** [comment]
Jag tror att detta har att göra med hur databastabellen är byggd. Det borde givetvis avspeglas i modellvalideringarna.

Man kan alltså sätta en validering på summan på inköpsdelar som kräver att inköpet är inom ett visst intervall. När vi ändå håller på borde det inte fungera att sätta ett negativt tal som summa på en inköpsdel, men såpass smart tror jag nog att jag redan varit.
