### ISSUE TITLE
direktlänk till "registrera ett inköp" på "min sida"

### ISSUE THREAD

**Issue by Frost** [datasektionen/cashflow-old#7]
Jag skulle gissa att 9/10 gånger när icke-admin loggar in på purchase/cashflow är det för att registrera ett inköp.

Därför borde det finnas en tydligt synlig länk som leder till den sidan direkt när man är inloggad.

**Comment by pbos** [comment]
Är det inte lika bra (bättre) att huvudsidan är att registrera inköp? Sedan borde det finnas en tydliga länkar till annat, men känns inte som att det behöver vara onödiga mellansteg efter man har loggat in.

**Comment by Frost** [comment]
Jag är inte så säker på att jag tycker det. Jag skulle vilja komma till någon form av "dashboard" när jag loggar in, och "min sida" funkar bra som en sån. Däremot tycker jag att det skulle behövas en lättåtkomlig länk för att komma till just inköpsregistreringen.

**Comment by Koronen** [comment]
Jag håller med @Frost här. Så länge länken till inköpsregistrering finns och är tydlig så föredrar jag nuvarande upplägg.

**Comment by pbos** [comment]
Ok, agreed, det låter bättre. Bara dashboarden är bra. :)

**Comment by Frost** [comment]
Givetvis kommer den bara bra... så fort någon designar den bra >.<

**Comment by Koronen** [comment]
La till länken nu iaf (cd60b24810294804b3ce9ede395e000bada75882).

**Comment by Frost** [comment]
Då stänger jag denna. En snygg dashboard känns mer som att det hör till UI-design och borde väl snarare vara en egen issue.
