### ISSUE TITLE
Menyn borde inte vara fixerad

### ISSUE THREAD

**Issue by Frost** [datasektionen/cashflow-old#72]
Om man försöker använda Cashflow på en telefon får man problem med att menyn är fixerad, dvs att den följer med när man scrollar.

Förslag till lösning: Plocka bort `.navbar-fixed-top` från menyn, och se till så att den hamnar där den ska ändå.

**Comment by vonbirdie** [comment]
Om menyn är minimerad ställer det väl inte till jätte mycket problem? Jag tycker det är rätt trevligt att kunna navigera utan att behöva scrolla längst upp på sidan. Att ta bort navbar-fixed-top kommer ställa till det en del på desktop klienterna och för att fixa till det kommer du få samma problem på mobilen igen. Enda sättet att komma runt detta så du har det som det är på desktop nu och inte ha det på mobilen är att ändra navbar-fixed-top för de media queries du vill eller att plocka bort klassen med js på mobiler. Även på mobiler kan du få lite knasiga saker om du inte har med stora delar av det navbar-fixed-top innehåller.

**Comment by Frost** [comment]
Problemet ligger lite i det att menyn dessutom inte är minimerad på mobilen, vilket gör det i stort sett omöjligt att lägga till inköp. Jag tror nog det skulle bli rätt mycket bättre om det problemet försvann.

**Comment by Frost** [comment]
Styrdokument-sidan verkar funka som den ska... jag felsöker.

**Comment by Frost** [comment]
Problemet är alltså att menyn inte minimeras på mobiler. Stänger denna, #73 är mer relevant.
