### ISSUE TITLE
Menyn är inte responsiv

### ISSUE THREAD

**Issue by Frost** [datasektionen/cashflow-old#73]
Om man går in på cashflow på en mobil tar menyn upp typ halva skärmen. Av någon anledning funkar inte bootstraps responsiva meny-greja.

**Comment by vonbirdie** [comment]
Vet inte riktigt var det började strula. Det fungerade ett bra tag vet jag, men slutade uppenbarligen där någon gång.

**Comment by Frost** [comment]
Dessutom verkar menyn ha tappat en padding-top.

**Comment by Frost** [comment]
https://github.com/metaskills/less-rails-bootstrap/pull/43 kanske kan lösa vårt problem, men när jag försökte med den, fick jag ett fel om att less inte kunde hitta någon `@primaryButtonBackground`-variabel. Jag har ingen koll på hur det där är uppsatt, och inte direkt tid att göra det... Har du tid, @luuse?

**Comment by vonbirdie** [comment]
Kollar på det någon dag. Peta på mig någon dag om jag glömmer bort.

**Comment by Frost** [comment]
Tack, det vore väldigt trevligt.

Det skumma var att jag fick det där `@primaryButtonBackground`-felet i datepickern när jag lade till det där, och inte någon annanstans. 

Förmodligen är det något simpelt jag missar eftersom jag inte har så bra koll på vare sig less eller bootstrap, men jag skulle tippa på att du skulle hitta och lösa problemet snabbare än jag.

**Comment by Frost** [comment]
Pull requesten jag länkade till är mergead sedan typ en vecka. 

Ping?
