### ISSUE TITLE
Flera budgetposter

### ISSUE THREAD

**Issue by maxnordlund** [datasektionen/cashflow-old#75]
Det vore trevligt om man kunde ha flera budgetposter per inköp. Nu måste man göra flera ärenden, och som vi alla vet är folk lata. Det medför konstigheter i budgetuppföljningen.

**Comment by Frost** [comment]
Det här vore förmodligen mest bara förvirrande. Jag tycker folk får lära sig att sluta vara lata. Annan input på detta? @Koronen @torandi

**Comment by Koronen** [comment]
Håller med. Folk får gärna sluta vara dåliga istället.

**Comment by Frost** [comment]
Dessutom vore det rätt bökigt att implementera, speciellt i kombination med ett förståeligt UI. Vore det inte dessutom konstigt att komma fram till var inköpet ifråga borde bokföras?
