### ISSUE TITLE
Ta bort fulhacket för att slippa explosioner i budget_posts#new

### ISSUE THREAD

**Issue by torandi** [datasektionen/cashflow-old#80]
Främst i budget_post/_form

**Comment by Frost** [comment]
Vad betyder detta, och hade du tänkt göra det någon gång snart, eller känner du för att kanske beskriva det i lite mer detalj här, så att någon annan kan ta tag i det?

**Comment by Frost** [comment]
Ping @torandi? Är detta fortfarande aktuellt?

**Comment by Koronen** [comment]
Det har kanske med MAGE-kopplingen att göra? [app/views/budget_posts/_form.html.haml#L5-8](https://github.com/datasektionen/cashflow/blob/51a6e3a4d34a59c0709b00df6c2f53c1e51119b6/app/views/budget_posts/_form.html.haml#L5-8)

**Comment by torandi** [comment]
Jadu, bra fråga. Det är förmodligen fortfarande aktuellt, och ska jag vara ärlig har jag ingen aning om vad som borde göras längre :S

**Comment by Koronen** [comment]
Då tycker jag att vi stänger denna tills vidare.

**Comment by Frost** [comment]
En sak jag skulle vilja göra där, är att vända på if-satsen. `unless ... else` är mest svårtolkat i mitt huvud.
