### ISSUE TITLE
[production][budget_posts#new] NoMethodError: undefined method `mage_number' for nil:NilClass

### ISSUE THREAD

**Issue by Ior** [datasektionen/cashflow-old#84]
[See this exception on Errbit](http://errbit.datasektionen.se:80/apps/1c895f4d33680942cb7d15f1fa725081/errs/4f99777c27314009cb0000cf)
# NoMethodError: undefined method `mage_number' for nil:NilClass
### URL

[http://cashflow.datasektionen.se/budget_posts/new](http://cashflow.datasektionen.se/budget_posts/new)"
### Where

budget_posts#new
### Occured

Apr 26  4:27pm
### Similar

1
## Params

```
{
  "action" => "new",
  "controller" => "budget_posts"
}
```
## Session

```
{
  "_csrf_token" => "rQCV4Tjq+ln+KWa+Al9c+fR711wjcnBjJFXrqoVpWbU=",
  "session_id" => "1628ad73c197d8bdb1b51d8753764777",
  "warden_user_user_key" => "[\"Person\", [\"7\"], \"\"]"
}
```
## Backtrace

```
5:  /app/views/budget_posts/_form.html.haml -> **block (2 levels) in _app_views_budget_posts__form_html_haml___2891597790885056509_22906220**
345:  [GEM_ROOT]/gems/haml-3.1.3/lib/haml/helpers.rb -> **call**
345:  [GEM_ROOT]/gems/haml-3.1.3/lib/haml/helpers.rb -> **block in capture_haml**
569:  [GEM_ROOT]/gems/haml-3.1.3/lib/haml/helpers.rb -> **with_haml_buffer**
341:  [GEM_ROOT]/gems/haml-3.1.3/lib/haml/helpers.rb -> **capture_haml**
61:  [GEM_ROOT]/gems/haml-3.1.3/lib/haml/helpers/xss_mods.rb -> **capture_haml_with_haml_xss**
19:  [GEM_ROOT]/bundler/gems/formtastic-bootstrap-85d7931c4c6c/lib/formtastic-bootstrap/helpers/fieldset_wrapper.rb -> **field_set_and_list_wrapping**
19:  [GEM_ROOT]/bundler/gems/formtastic-bootstrap-85d7931c4c6c/lib/formtastic-bootstrap/helpers/inputs_helper.rb -> **inputs**
2:  /app/views/budget_posts/_form.html.haml -> **block in _app_views_budget_posts__form_html_haml___2891597790885056509_22906220**
180:  [GEM_ROOT]/gems/haml-3.1.3/lib/haml/helpers/action_view_mods.rb -> **call**
180:  [GEM_ROOT]/gems/haml-3.1.3/lib/haml/helpers/action_view_mods.rb -> **block (2 levels) in form_for_with_haml**
255:  [GEM_ROOT]/gems/haml-3.1.3/lib/haml/helpers.rb -> **with_tabs**
180:  [GEM_ROOT]/gems/haml-3.1.3/lib/haml/helpers/action_view_mods.rb -> **block in form_for_with_haml**
40:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/helpers/capture_helper.rb -> **block in capture**
187:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/helpers/capture_helper.rb -> **with_output_buffer**
109:  [GEM_ROOT]/gems/haml-3.1.3/lib/haml/helpers/xss_mods.rb -> **with_output_buffer_with_haml_xss**
40:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/helpers/capture_helper.rb -> **capture**
105:  [GEM_ROOT]/gems/haml-3.1.3/lib/haml/helpers/action_view_mods.rb -> **capture_with_haml**
590:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/helpers/form_helper.rb -> **fields_for**
373:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/helpers/form_helper.rb -> **form_for**
182:  [GEM_ROOT]/gems/haml-3.1.3/lib/haml/helpers/action_view_mods.rb -> **form_for_with_haml**
132:  [GEM_ROOT]/gems/haml-3.1.3/lib/haml/helpers/xss_mods.rb -> **form_for_with_haml_xss**
161:  [GEM_ROOT]/gems/formtastic-2.0.2/lib/formtastic/helpers/form_helper.rb -> **block in semantic_form_for**
192:  [GEM_ROOT]/gems/formtastic-2.0.2/lib/formtastic/helpers/form_helper.rb -> **with_custom_field_error_proc**
160:  [GEM_ROOT]/gems/formtastic-2.0.2/lib/formtastic/helpers/form_helper.rb -> **semantic_form_for**
1:  /app/views/budget_posts/_form.html.haml -> **_app_views_budget_posts__form_html_haml___2891597790885056509_22906220**
171:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/template.rb -> **block in render**
55:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/notifications.rb -> **instrument**
169:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/template.rb -> **render**
256:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/partial_renderer.rb -> **render_partial**
228:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/partial_renderer.rb -> **block (2 levels) in render**
33:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/abstract_renderer.rb -> **block in instrument**
53:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/notifications.rb -> **block in instrument**
21:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/notifications/instrumenter.rb -> **instrument**
53:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/notifications.rb -> **instrument**
33:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/abstract_renderer.rb -> **instrument**
227:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/partial_renderer.rb -> **block in render**
22:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/abstract_renderer.rb -> **wrap_formats**
219:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/partial_renderer.rb -> **render**
41:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/renderer.rb -> **render_partial**
15:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/renderer.rb -> **render**
24:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/helpers/rendering_helper.rb -> **render**
11:  [GEM_ROOT]/gems/haml-3.1.3/lib/haml/helpers/action_view_mods.rb -> **block in render_with_haml**
90:  [GEM_ROOT]/gems/haml-3.1.3/lib/haml/helpers.rb -> **non_haml**
11:  [GEM_ROOT]/gems/haml-3.1.3/lib/haml/helpers/action_view_mods.rb -> **render_with_haml**
2:  /app/views/budget_posts/new.html.haml -> **_app_views_budget_posts_new_html_haml__2615520332696510546_50961620**
171:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/template.rb -> **block in render**
55:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/notifications.rb -> **instrument**
169:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/template.rb -> **render**
40:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/template_renderer.rb -> **block (2 levels) in render_template**
33:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/abstract_renderer.rb -> **block in instrument**
53:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/notifications.rb -> **block in instrument**
21:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/notifications/instrumenter.rb -> **instrument**
53:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/notifications.rb -> **instrument**
33:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/abstract_renderer.rb -> **instrument**
39:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/template_renderer.rb -> **block in render_template**
47:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/template_renderer.rb -> **render_with_layout**
38:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/template_renderer.rb -> **render_template**
12:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/template_renderer.rb -> **block in render**
22:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/abstract_renderer.rb -> **wrap_formats**
9:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/template_renderer.rb -> **render**
36:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/renderer.rb -> **render_template**
17:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_view/renderer/renderer.rb -> **render**
120:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/abstract_controller/rendering.rb -> **_render_template**
250:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/streaming.rb -> **_render_template**
114:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/abstract_controller/rendering.rb -> **render_to_body**
30:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/renderers.rb -> **render_to_body**
43:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/compatibility.rb -> **render_to_body**
99:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/abstract_controller/rendering.rb -> **render**
16:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/rendering.rb -> **render**
40:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/instrumentation.rb -> **block (2 levels) in render**
5:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/core_ext/benchmark.rb -> **block in ms**
310:  /usr/local/rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/benchmark.rb -> **realtime**
5:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/core_ext/benchmark.rb -> **ms**
40:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/instrumentation.rb -> **block in render**
78:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/instrumentation.rb -> **cleanup_view_runtime**
24:  [GEM_ROOT]/gems/activerecord-3.1.3/lib/active_record/railties/controller_runtime.rb -> **cleanup_view_runtime**
39:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/instrumentation.rb -> **render**
10:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/implicit_render.rb -> **default_render**
268:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/mime_responds.rb -> **block in retrieve_response_from_mimes**
195:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/mime_responds.rb -> **call**
195:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/mime_responds.rb -> **respond_to**
34:  /app/controllers/budget_posts_controller.rb -> **new**
4:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/implicit_render.rb -> **send_action**
167:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/abstract_controller/base.rb -> **process_action**
10:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/rendering.rb -> **process_action**
18:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/abstract_controller/callbacks.rb -> **block in process_action**
461:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/callbacks.rb -> **_run__4049682934353759258__process_action__1727552755061785754__callbacks**
386:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/callbacks.rb -> **_run_process_action_callbacks**
81:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/callbacks.rb -> **run_callbacks**
17:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/abstract_controller/callbacks.rb -> **process_action**
17:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/rescue.rb -> **process_action**
30:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
53:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/notifications.rb -> **block in instrument**
21:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/notifications/instrumenter.rb -> **instrument**
53:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/notifications.rb -> **instrument**
29:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/instrumentation.rb -> **process_action**
201:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/params_wrapper.rb -> **process_action**
18:  [GEM_ROOT]/gems/activerecord-3.1.3/lib/active_record/railties/controller_runtime.rb -> **process_action**
121:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/abstract_controller/base.rb -> **process**
45:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/abstract_controller/rendering.rb -> **process**
193:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal.rb -> **dispatch**
14:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/rack_delegation.rb -> **dispatch**
236:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal.rb -> **block in action**
65:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb -> **call**
65:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb -> **dispatch**
29:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb -> **call**
152:  [GEM_ROOT]/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb -> **block in call**
96:  [GEM_ROOT]/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb -> **block in recognize**
75:  [GEM_ROOT]/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb -> **optimized_each**
95:  [GEM_ROOT]/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb -> **recognize**
141:  [GEM_ROOT]/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb -> **call**
532:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb -> **call**
44:  [GEM_ROOT]/gems/oa-core-0.3.2/lib/omniauth/strategy.rb -> **call!**
30:  [GEM_ROOT]/gems/oa-core-0.3.2/lib/omniauth/strategy.rb -> **call**
35:  [GEM_ROOT]/gems/warden-1.0.6/lib/warden/manager.rb -> **block in call**
34:  [GEM_ROOT]/gems/warden-1.0.6/lib/warden/manager.rb -> **catch**
34:  [GEM_ROOT]/gems/warden-1.0.6/lib/warden/manager.rb -> **call**
17:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/best_standards_support.rb -> **call**
23:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/etag.rb -> **call**
25:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/conditionalget.rb -> **call**
14:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/head.rb -> **call**
21:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/params_parser.rb -> **call**
247:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/flash.rb -> **call**
195:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/session/abstract/id.rb -> **context**
190:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/session/abstract/id.rb -> **call**
331:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/cookies.rb -> **call**
64:  [GEM_ROOT]/gems/activerecord-3.1.3/lib/active_record/query_cache.rb -> **call**
477:  [GEM_ROOT]/gems/activerecord-3.1.3/lib/active_record/connection_adapters/abstract/connection_pool.rb -> **call**
29:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
392:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/callbacks.rb -> **_run_call_callbacks**
81:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/callbacks.rb -> **run_callbacks**
28:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/callbacks.rb -> **call**
101:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/sendfile.rb -> **call**
48:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/remote_ip.rb -> **call**
47:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
13:  [GEM_ROOT]/gems/railties-3.1.3/lib/rails/rack/logger.rb -> **call**
24:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/methodoverride.rb -> **call**
17:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/runtime.rb -> **call**
72:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/cache/strategy/local_cache.rb -> **call**
15:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/lock.rb -> **call**
53:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/static.rb -> **call**
136:  [GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb -> **forward**
245:  [GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb -> **fetch**
185:  [GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb -> **lookup**
66:  [GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb -> **call!**
51:  [GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb -> **call**
456:  [GEM_ROOT]/gems/railties-3.1.3/lib/rails/engine.rb -> **call**
30:  [GEM_ROOT]/gems/railties-3.1.3/lib/rails/railtie/configurable.rb -> **method_missing**
528:  [GEM_ROOT]/gems/unicorn-4.1.1/lib/unicorn/http_server.rb -> **process_client**
600:  [GEM_ROOT]/gems/unicorn-4.1.1/lib/unicorn/http_server.rb -> **worker_loop**
485:  [GEM_ROOT]/gems/unicorn-4.1.1/lib/unicorn/http_server.rb -> **spawn_missing_workers**
135:  [GEM_ROOT]/gems/unicorn-4.1.1/lib/unicorn/http_server.rb -> **start**
121:  [GEM_ROOT]/gems/unicorn-4.1.1/bin/unicorn -> **<top (required)>**
19:  [GEM_ROOT]/bin/unicorn -> **load**
19:  [GEM_ROOT]/bin/unicorn -> **<main>**

```
## Environment

<table>

<tr>
<td>REMOTE_ADDR:</td>
<td>127.0.0.1</td>
</tr>

<tr>
<td>REQUEST_METHOD:</td>
<td>GET</td>
</tr>

<tr>
<td>REQUEST_PATH:</td>
<td>/budget_posts/new</td>
</tr>

<tr>
<td>PATH_INFO:</td>
<td>/budget_posts/new</td>
</tr>

<tr>
<td>REQUEST_URI:</td>
<td>/budget_posts/new</td>
</tr>

<tr>
<td>SERVER_PROTOCOL:</td>
<td>HTTP/1.0</td>
</tr>

<tr>
<td>HTTP_VERSION:</td>
<td>HTTP/1.0</td>
</tr>

<tr>
<td>HTTP_HOST:</td>
<td>cashflow.datasektionen.se</td>
</tr>

<tr>
<td>HTTP_X_REAL_IP:</td>
<td>::ffff:130.229.173.254</td>
</tr>

<tr>
<td>HTTP_X_FORWARDED_FOR:</td>
<td>::ffff:130.229.173.254</td>
</tr>

<tr>
<td>HTTP_CONNECTION:</td>
<td>close</td>
</tr>

<tr>
<td>HTTP_USER_AGENT:</td>
<td>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:11.0) Gecko/20100101 Firefox/11.0</td>
</tr>

<tr>
<td>HTTP_ACCEPT:</td>
<td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td>
</tr>

<tr>
<td>HTTP_ACCEPT_LANGUAGE:</td>
<td>en-us,en;q=0.5</td>
</tr>

<tr>
<td>HTTP_ACCEPT_ENCODING:</td>
<td>gzip, deflate</td>
</tr>

<tr>
<td>HTTP_COOKIE:</td>
<td>__utma=239681174.1667054593.1314018351.1333710547.1335214887.11; __utmz=239681174.1323612781.7.2.utmcsr=facebook.com|utmccn=(referral)|utmcmd=referral|utmcct=/l.php; _cashflow_session=BAh7CEkiD3Nlc3Npb25faWQGOgZFRkkiJTE2MjhhZDczYzE5N2Q4YmRiMWI1MWQ4NzUzNzY0Nzc3BjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMXJRQ1Y0VGpxK2xuK0tXYStBbDljK2ZSNzExd2pjbkJqSkZYcnFvVnBXYlU9BjsARkkiGXdhcmRlbi51c2VyLnVzZXIua2V5BjsAVFsISSILUGVyc29uBjsARlsGaQww--3c9f2d2ac64e6b525d5be44d3c0a0d50a91eb283; __utma=195911998.607106909.1335449745.1335449745.1335449745.1; __utmb=195911998.14.10.1335449745; __utmc=195911998; __utmz=195911998.1335449745.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)</td>
</tr>

<tr>
<td>rack_url_scheme:</td>
<td>http</td>
</tr>

<tr>
<td>SERVER_NAME:</td>
<td>cashflow.datasektionen.se</td>
</tr>

<tr>
<td>SERVER_PORT:</td>
<td>80</td>
</tr>

<tr>
<td>key:</td>
<td>action_dispatch.request.query_parameters</td>
</tr>

<tr>
<td>rack_input:</td>
<td>#<StringIO:0x00000002863560></td>
</tr>

<tr>
<td>rack_errors:</td>
<td>#<File:0x0000000196b760></td>
</tr>

<tr>
<td>rack_multiprocess:</td>
<td>true</td>
</tr>

<tr>
<td>rack_multithread:</td>
<td>false</td>
</tr>

<tr>
<td>rack_run_once:</td>
<td>false</td>
</tr>

<tr>
<td>rack_version:</td>
<td>["1", "1"]</td>
</tr>

<tr>
<td>SERVER_SOFTWARE:</td>
<td>Unicorn 4.1.1</td>
</tr>

<tr>
<td>rack_logger:</td>
<td>#<Logger:0x0000000241bc00></td>
</tr>

<tr>
<td>action_dispatch_routes:</td>
<td>#<ActionDispatch::Routing::RouteSet:0x000000040640b0></td>
</tr>

<tr>
<td>action_dispatch_parameter_filter:</td>
<td>["password"]</td>
</tr>

<tr>
<td>action_dispatch_secret_token:</td>
<td>09a55b6ac022b75d133d9111e389542ba7f36b18c71e1eea303e7cf1dc81fa6ee59e5f6d0e7b68770927737c5bf2e8ffc4f43858d381f0e90ef027041ab8ba23</td>
</tr>

<tr>
<td>action_dispatch_show_exceptions:</td>
<td>true</td>
</tr>

<tr>
<td>rack-cache_cache_key:</td>
<td>Rack::Cache::Key</td>
</tr>

<tr>
<td>rack-cache_verbose:</td>
<td>true</td>
</tr>

<tr>
<td>rack-cache_storage:</td>
<td>#<Rack::Cache::Storage:0x00000002beb048></td>
</tr>

<tr>
<td>rack-cache_metastore:</td>
<td>rails:/</td>
</tr>

<tr>
<td>rack-cache_entitystore:</td>
<td>rails:/</td>
</tr>

<tr>
<td>rack-cache_default_ttl:</td>
<td>0</td>
</tr>

<tr>
<td>rack-cache_ignore_headers:</td>
<td>["Set-Cookie"]</td>
</tr>

<tr>
<td>rack-cache_private_headers:</td>
<td>["Authorization", "Cookie"]</td>
</tr>

<tr>
<td>rack-cache_allow_reload:</td>
<td>false</td>
</tr>

<tr>
<td>rack-cache_allow_revalidate:</td>
<td>false</td>
</tr>

<tr>
<td>rack-cache_use_native_ttl:</td>
<td>false</td>
</tr>

<tr>
<td>action_dispatch_remote_ip:</td>
<td>::ffff:130.229.173.254</td>
</tr>

<tr>
<td>rack_session:</td>
<td>{"session_id"=>"1628ad73c197d8bdb1b51d8753764777", "_csrf_token"=>"rQCV4Tjq+ln+KWa+Al9c+fR711wjcnBjJFXrqoVpWbU=", "warden_user_user_key"=>"[\"Person\", [\"7\"], \"\"]"}</td>
</tr>

<tr>
<td>rack_session_options:</td>
<td>{"key"=>"expire_after", "path"=>"/", "secure"=>"false", "httponly"=>"true", "defer"=>"false", "renew"=>"false", "coder"=>"#<Rack::Session::Cookie::Base64::Marshal:0x00000004b953f8>", "id"=>"1628ad73c197d8bdb1b51d8753764777"}</td>
</tr>

<tr>
<td>rack_request_cookie_hash:</td>
<td>{"__utma"=>"239681174.1667054593.1314018351.1333710547.1335214887.11", "__utmz"=>"239681174.1323612781.7.2.utmcsr=facebook.com|utmccn=(referral)|utmcmd=referral|utmcct=/l.php", "_cashflow_session"=>"BAh7CEkiD3Nlc3Npb25faWQGOgZFRkkiJTE2MjhhZDczYzE5N2Q4YmRiMWI1MWQ4NzUzNzY0Nzc3BjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMXJRQ1Y0VGpxK2xuK0tXYStBbDljK2ZSNzExd2pjbkJqSkZYcnFvVnBXYlU9BjsARkkiGXdhcmRlbi51c2VyLnVzZXIua2V5BjsAVFsISSILUGVyc29uBjsARlsGaQww--3c9f2d2ac64e6b525d5be44d3c0a0d50a91eb283", "__utmb"=>"195911998.14.10.1335449745", "__utmc"=>"195911998"}</td>
</tr>

<tr>
<td>rack_request_cookie_string:</td>
<td>__utma=239681174.1667054593.1314018351.1333710547.1335214887.11; __utmz=239681174.1323612781.7.2.utmcsr=facebook.com|utmccn=(referral)|utmcmd=referral|utmcct=/l.php; _cashflow_session=BAh7CEkiD3Nlc3Npb25faWQGOgZFRkkiJTE2MjhhZDczYzE5N2Q4YmRiMWI1MWQ4NzUzNzY0Nzc3BjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMXJRQ1Y0VGpxK2xuK0tXYStBbDljK2ZSNzExd2pjbkJqSkZYcnFvVnBXYlU9BjsARkkiGXdhcmRlbi51c2VyLnVzZXIua2V5BjsAVFsISSILUGVyc29uBjsARlsGaQww--3c9f2d2ac64e6b525d5be44d3c0a0d50a91eb283; __utma=195911998.607106909.1335449745.1335449745.1335449745.1; __utmb=195911998.14.10.1335449745; __utmc=195911998; __utmz=195911998.1335449745.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)</td>
</tr>

<tr>
<td>action_dispatch_cookies:</td>
<td>#<ActionDispatch::Cookies::CookieJar:0x000000061ba6b0></td>
</tr>

<tr>
<td>action_dispatch_request_unsigned_session_cookie:</td>
<td>{"session_id"=>"1628ad73c197d8bdb1b51d8753764777", "_csrf_token"=>"rQCV4Tjq+ln+KWa+Al9c+fR711wjcnBjJFXrqoVpWbU=", "warden_user_user_key"=>"[\"Person\", [\"7\"], \"\"]"}</td>
</tr>

<tr>
<td>warden:</td>
<td>Warden::Proxy:51232660 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[]}, :intercept_401=>false, :failure_app=>Devise::FailureApp}</td>
</tr>

<tr>
<td>action_dispatch_request_path_parameters:</td>
<td>{"action"=>"new", "controller"=>"budget_posts"}</td>
</tr>

<tr>
<td>action_controller_instance:</td>
<td>#<BudgetPostsController:0x0000000618b608></td>
</tr>

<tr>
<td>action_dispatch_request_parameters:</td>
<td>{"action"=>"new", "controller"=>"budget_posts"}</td>
</tr>

<tr>
<td>action_dispatch_request_formats:</td>
<td>["text/html"]</td>
</tr>

</table>

**Comment by torandi** [comment]
15:16:07 <   Torandi> hum.. den ena vet jag att jag har kollat på tidigare, minns dock inte om jag 
                      löste den
15:23:04 <   Torandi> Frost: https://github.com/datasektionen/cashflow/issues/84 är "löst"
15:23:06 <      Hink> Torandi: [Url] Issue #84: [production][budget_posts#new] NoMethodError: 
                      undefined method `mage_number' for nil:NilClass · datasektionen/cashflow · 
                      GitHub | http://bit.ly/LNorsw
15:23:10 <   Torandi> "fixad" är nog korrekta termen
15:23:17 <   Torandi> men det är ett hack
15:24:03 <   Torandi> se app/c/budget_posts_controller#new och app/view/bu_po/_form.html.haml
15:25:10 <   Torandi> problemet är att för att kunna välja arr för en budgetpost måste man kunna 
                      lista alla arrangemang från mage. Men arr är per nämnd ju
15:25:21 <   Torandi> och nämnd är inte specat när man börjar skapa en ny budget_post
15:25:27 <   Torandi> nu är det hackat runt
15:25:51 <   Torandi> den snygga lösningen är nog att man skapar en ny budgetpost genom att gå 
                      affärsenhet->lägg till budgetpost
15:26:33 <   Torandi> dvs affärsenhet är specad när man skapar budgetposten

**Comment by Frost** [comment]
Så, om denna är fixad, stänger jag den nu. Vill du bygga den snygga lösningen (och det vore väldigt trevligt), kan du öppna en separat issue för det.
