### ISSUE TITLE
[production][purchases#keep] RuntimeError: An error occured when pushing #<Purchase id: 338, description: "PR-fika", workflow_...

### ISSUE THREAD

**Issue by Ior** [datasektionen/cashflow-old#85]
[See this exception on Errbit](http://errbit.datasektionen.se:80/apps/1c895f4d33680942cb7d15f1fa725081/errs/4f99a4b127314009cb0000d7)
# RuntimeError: An error occured when pushing #<Purchase id: 338, description: "PR-fika", workflow_state: "confirmed", person_id: 67, purchased_at: "2011-11-16", slug: "ms2011-338", created_at: "2012-02-24 17:11:10", updated_at: "2012-04-26 19:40:24", budget_post_id: 88, year: 2011> to MAGE (push returned false)
### URL

[http://cashflow.datasektionen.se/inkop/ms2011-338/keep](http://cashflow.datasektionen.se/inkop/ms2011-338/keep)"
### Where

purchases#keep
### Occured

Apr 26  7:40pm
### Similar

0
## Params

```
{
  "_method" => "put",
  "action" => "keep",
  "authenticity_token" => "JHP2yBXymtdHya1JnGRQ0R3xnvBv7QoSHfyop907j38=",
  "controller" => "purchases",
  "id" => "ms2011-338"
}
```
## Session

```
{
  "_csrf_token" => "JHP2yBXymtdHya1JnGRQ0R3xnvBv7QoSHfyop907j38=",
  "session_id" => "e245340ebd16f14c104edbf76972d18b",
  "warden_user_user_key" => "[\"Person\", [\"67\"], \"\"]"
}
```
## Backtrace

```
13:  /app/models/purchase_observer.rb -> **after_keep**
232:  [GEM_ROOT]/gems/activemodel-3.1.3/lib/active_model/observing.rb -> **update**
74:  [GEM_ROOT]/gems/activemodel-3.1.3/lib/active_model/observing.rb -> **block in notify_observers**
74:  [GEM_ROOT]/gems/activemodel-3.1.3/lib/active_model/observing.rb -> **each**
74:  [GEM_ROOT]/gems/activemodel-3.1.3/lib/active_model/observing.rb -> **notify_observers**
114:  [GEM_ROOT]/gems/activemodel-3.1.3/lib/active_model/observing.rb -> **notify_observers**
81:  /app/models/purchase.rb -> **keep**
253:  [GEM_ROOT]/gems/workflow-0.8.1/lib/workflow.rb -> **run_action_callback**
180:  [GEM_ROOT]/gems/workflow-0.8.1/lib/workflow.rb -> **process_event!**
133:  [GEM_ROOT]/gems/workflow-0.8.1/lib/workflow.rb -> **block (4 levels) in workflow**
126:  /app/controllers/purchases_controller.rb -> **keep**
4:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/implicit_render.rb -> **send_action**
167:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/abstract_controller/base.rb -> **process_action**
10:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/rendering.rb -> **process_action**
18:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/abstract_controller/callbacks.rb -> **block in process_action**
461:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/callbacks.rb -> **_run__2341668644444225500__process_action__1918832751252362009__callbacks**
386:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/callbacks.rb -> **_run_process_action_callbacks**
81:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/callbacks.rb -> **run_callbacks**
17:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/abstract_controller/callbacks.rb -> **process_action**
17:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/rescue.rb -> **process_action**
30:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
53:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/notifications.rb -> **block in instrument**
21:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/notifications/instrumenter.rb -> **instrument**
53:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/notifications.rb -> **instrument**
29:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/instrumentation.rb -> **process_action**
201:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/params_wrapper.rb -> **process_action**
18:  [GEM_ROOT]/gems/activerecord-3.1.3/lib/active_record/railties/controller_runtime.rb -> **process_action**
121:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/abstract_controller/base.rb -> **process**
45:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/abstract_controller/rendering.rb -> **process**
193:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal.rb -> **dispatch**
14:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/rack_delegation.rb -> **dispatch**
236:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal.rb -> **block in action**
65:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb -> **call**
65:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb -> **dispatch**
29:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb -> **call**
152:  [GEM_ROOT]/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb -> **block in call**
96:  [GEM_ROOT]/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb -> **block in recognize**
82:  [GEM_ROOT]/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb -> **optimized_each**
95:  [GEM_ROOT]/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb -> **recognize**
141:  [GEM_ROOT]/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb -> **call**
532:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb -> **call**
44:  [GEM_ROOT]/gems/oa-core-0.3.2/lib/omniauth/strategy.rb -> **call!**
30:  [GEM_ROOT]/gems/oa-core-0.3.2/lib/omniauth/strategy.rb -> **call**
35:  [GEM_ROOT]/gems/warden-1.0.6/lib/warden/manager.rb -> **block in call**
34:  [GEM_ROOT]/gems/warden-1.0.6/lib/warden/manager.rb -> **catch**
34:  [GEM_ROOT]/gems/warden-1.0.6/lib/warden/manager.rb -> **call**
17:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/best_standards_support.rb -> **call**
23:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/etag.rb -> **call**
35:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/conditionalget.rb -> **call**
14:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/head.rb -> **call**
21:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/params_parser.rb -> **call**
247:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/flash.rb -> **call**
195:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/session/abstract/id.rb -> **context**
190:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/session/abstract/id.rb -> **call**
331:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/cookies.rb -> **call**
64:  [GEM_ROOT]/gems/activerecord-3.1.3/lib/active_record/query_cache.rb -> **call**
477:  [GEM_ROOT]/gems/activerecord-3.1.3/lib/active_record/connection_adapters/abstract/connection_pool.rb -> **call**
29:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
392:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/callbacks.rb -> **_run_call_callbacks**
81:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/callbacks.rb -> **run_callbacks**
28:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/callbacks.rb -> **call**
101:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/sendfile.rb -> **call**
48:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/remote_ip.rb -> **call**
47:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
13:  [GEM_ROOT]/gems/railties-3.1.3/lib/rails/rack/logger.rb -> **call**
24:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/methodoverride.rb -> **call**
17:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/runtime.rb -> **call**
72:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/cache/strategy/local_cache.rb -> **call**
15:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/lock.rb -> **call**
53:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/static.rb -> **call**
136:  [GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb -> **forward**
143:  [GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb -> **pass**
155:  [GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb -> **invalidate**
71:  [GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb -> **call!**
51:  [GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb -> **call**
456:  [GEM_ROOT]/gems/railties-3.1.3/lib/rails/engine.rb -> **call**
30:  [GEM_ROOT]/gems/railties-3.1.3/lib/rails/railtie/configurable.rb -> **method_missing**
528:  [GEM_ROOT]/gems/unicorn-4.1.1/lib/unicorn/http_server.rb -> **process_client**
600:  [GEM_ROOT]/gems/unicorn-4.1.1/lib/unicorn/http_server.rb -> **worker_loop**
485:  [GEM_ROOT]/gems/unicorn-4.1.1/lib/unicorn/http_server.rb -> **spawn_missing_workers**
135:  [GEM_ROOT]/gems/unicorn-4.1.1/lib/unicorn/http_server.rb -> **start**
121:  [GEM_ROOT]/gems/unicorn-4.1.1/bin/unicorn -> **<top (required)>**
19:  [GEM_ROOT]/bin/unicorn -> **load**
19:  [GEM_ROOT]/bin/unicorn -> **<main>**

```
## Environment

<table>

<tr>
<td>REMOTE_ADDR:</td>
<td>127.0.0.1</td>
</tr>

<tr>
<td>REQUEST_METHOD:</td>
<td>PUT</td>
</tr>

<tr>
<td>REQUEST_PATH:</td>
<td>/inkop/ms2011-338/keep</td>
</tr>

<tr>
<td>PATH_INFO:</td>
<td>/inkop/ms2011-338/keep</td>
</tr>

<tr>
<td>REQUEST_URI:</td>
<td>/inkop/ms2011-338/keep</td>
</tr>

<tr>
<td>SERVER_PROTOCOL:</td>
<td>HTTP/1.0</td>
</tr>

<tr>
<td>HTTP_VERSION:</td>
<td>HTTP/1.0</td>
</tr>

<tr>
<td>HTTP_HOST:</td>
<td>cashflow.datasektionen.se</td>
</tr>

<tr>
<td>HTTP_X_REAL_IP:</td>
<td>::ffff:130.229.149.32</td>
</tr>

<tr>
<td>HTTP_X_FORWARDED_FOR:</td>
<td>::ffff:130.229.149.32</td>
</tr>

<tr>
<td>HTTP_CONNECTION:</td>
<td>close</td>
</tr>

<tr>
<td>CONTENT_LENGTH:</td>
<td>77</td>
</tr>

<tr>
<td>HTTP_CACHE_CONTROL:</td>
<td>max-age=0</td>
</tr>

<tr>
<td>HTTP_ORIGIN:</td>
<td>http://cashflow.datasektionen.se</td>
</tr>

<tr>
<td>HTTP_USER_AGENT:</td>
<td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.165 Safari/535.19</td>
</tr>

<tr>
<td>CONTENT_TYPE:</td>
<td>application/x-www-form-urlencoded</td>
</tr>

<tr>
<td>HTTP_ACCEPT:</td>
<td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td>
</tr>

<tr>
<td>HTTP_REFERER:</td>
<td>http://cashflow.datasektionen.se/inkop/ms2011-338</td>
</tr>

<tr>
<td>HTTP_ACCEPT_ENCODING:</td>
<td>gzip,deflate,sdch</td>
</tr>

<tr>
<td>HTTP_ACCEPT_LANGUAGE:</td>
<td>en-US,en;q=0.8</td>
</tr>

<tr>
<td>HTTP_ACCEPT_CHARSET:</td>
<td>ISO-8859-1,utf-8;q=0.7,*;q=0.3</td>
</tr>

<tr>
<td>HTTP_COOKIE:</td>
<td>__utma=239681174.1180292426.1326719988.1334759878.1334824600.50; __utmz=239681174.1326719988.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _cashflow_session=BAh7CEkiD3Nlc3Npb25faWQGOgZFRkkiJWUyNDUzNDBlYmQxNmYxNGMxMDRlZGJmNzY5NzJkMThiBjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMUpIUDJ5Qlh5bXRkSHlhMUpuR1JRMFIzeG52QnY3UW9TSGZ5b3A5MDdqMzg9BjsARkkiGXdhcmRlbi51c2VyLnVzZXIua2V5BjsAVFsISSILUGVyc29uBjsARlsGaUgw--6bbc5ffb34825d01d3802a4a014181ac24540616; __utma=195911998.200911748.1328475493.1335461169.1335468436.11; __utmb=195911998.7.10.1335468436; __utmc=195911998; __utmz=195911998.1328475493.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)</td>
</tr>

<tr>
<td>rack_url_scheme:</td>
<td>http</td>
</tr>

<tr>
<td>SERVER_NAME:</td>
<td>cashflow.datasektionen.se</td>
</tr>

<tr>
<td>SERVER_PORT:</td>
<td>80</td>
</tr>

<tr>
<td>key:</td>
<td>action_dispatch.request.query_parameters</td>
</tr>

<tr>
<td>rack_input:</td>
<td>#<Unicorn::TeeInput:0x000000042c37c0></td>
</tr>

<tr>
<td>rack_errors:</td>
<td>#<File:0x000000011ad758></td>
</tr>

<tr>
<td>rack_multiprocess:</td>
<td>true</td>
</tr>

<tr>
<td>rack_multithread:</td>
<td>false</td>
</tr>

<tr>
<td>rack_run_once:</td>
<td>false</td>
</tr>

<tr>
<td>rack_version:</td>
<td>["1", "1"]</td>
</tr>

<tr>
<td>SERVER_SOFTWARE:</td>
<td>Unicorn 4.1.1</td>
</tr>

<tr>
<td>rack_logger:</td>
<td>#<Logger:0x0000000192f210></td>
</tr>

<tr>
<td>action_dispatch_routes:</td>
<td>#<ActionDispatch::Routing::RouteSet:0x00000003e0b570></td>
</tr>

<tr>
<td>action_dispatch_parameter_filter:</td>
<td>["password"]</td>
</tr>

<tr>
<td>action_dispatch_secret_token:</td>
<td>09a55b6ac022b75d133d9111e389542ba7f36b18c71e1eea303e7cf1dc81fa6ee59e5f6d0e7b68770927737c5bf2e8ffc4f43858d381f0e90ef027041ab8ba23</td>
</tr>

<tr>
<td>action_dispatch_show_exceptions:</td>
<td>true</td>
</tr>

<tr>
<td>rack-cache_cache_key:</td>
<td>Rack::Cache::Key</td>
</tr>

<tr>
<td>rack-cache_verbose:</td>
<td>true</td>
</tr>

<tr>
<td>rack-cache_storage:</td>
<td>#<Rack::Cache::Storage:0x00000002490c58></td>
</tr>

<tr>
<td>rack-cache_metastore:</td>
<td>rails:/</td>
</tr>

<tr>
<td>rack-cache_entitystore:</td>
<td>rails:/</td>
</tr>

<tr>
<td>rack-cache_default_ttl:</td>
<td>0</td>
</tr>

<tr>
<td>rack-cache_ignore_headers:</td>
<td>["Set-Cookie"]</td>
</tr>

<tr>
<td>rack-cache_private_headers:</td>
<td>["Authorization", "Cookie"]</td>
</tr>

<tr>
<td>rack-cache_allow_reload:</td>
<td>false</td>
</tr>

<tr>
<td>rack-cache_allow_revalidate:</td>
<td>false</td>
</tr>

<tr>
<td>rack-cache_use_native_ttl:</td>
<td>false</td>
</tr>

<tr>
<td>rack_request_form_input:</td>
<td>#<Unicorn::TeeInput:0x000000042c37c0></td>
</tr>

<tr>
<td>rack_request_form_hash:</td>
<td>{"_method"=>"put", "authenticity_token"=>"JHP2yBXymtdHya1JnGRQ0R3xnvBv7QoSHfyop907j38="}</td>
</tr>

<tr>
<td>rack_methodoverride_original_method:</td>
<td>POST</td>
</tr>

<tr>
<td>action_dispatch_remote_ip:</td>
<td>::ffff:130.229.149.32</td>
</tr>

<tr>
<td>rack_session:</td>
<td>{"session_id"=>"e245340ebd16f14c104edbf76972d18b", "_csrf_token"=>"JHP2yBXymtdHya1JnGRQ0R3xnvBv7QoSHfyop907j38=", "warden_user_user_key"=>"[\"Person\", [\"67\"], \"\"]"}</td>
</tr>

<tr>
<td>rack_session_options:</td>
<td>{"key"=>"expire_after", "path"=>"/", "secure"=>"false", "httponly"=>"true", "defer"=>"false", "renew"=>"false", "coder"=>"#<Rack::Session::Cookie::Base64::Marshal:0x000000042573b8>", "id"=>"e245340ebd16f14c104edbf76972d18b"}</td>
</tr>

<tr>
<td>rack_request_cookie_hash:</td>
<td>{"__utma"=>"239681174.1180292426.1326719988.1334759878.1334824600.50", "__utmz"=>"239681174.1326719988.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)", "_cashflow_session"=>"BAh7CEkiD3Nlc3Npb25faWQGOgZFRkkiJWUyNDUzNDBlYmQxNmYxNGMxMDRlZGJmNzY5NzJkMThiBjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMUpIUDJ5Qlh5bXRkSHlhMUpuR1JRMFIzeG52QnY3UW9TSGZ5b3A5MDdqMzg9BjsARkkiGXdhcmRlbi51c2VyLnVzZXIua2V5BjsAVFsISSILUGVyc29uBjsARlsGaUgw--6bbc5ffb34825d01d3802a4a014181ac24540616", "__utmb"=>"195911998.7.10.1335468436", "__utmc"=>"195911998"}</td>
</tr>

<tr>
<td>rack_request_cookie_string:</td>
<td>__utma=239681174.1180292426.1326719988.1334759878.1334824600.50; __utmz=239681174.1326719988.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _cashflow_session=BAh7CEkiD3Nlc3Npb25faWQGOgZFRkkiJWUyNDUzNDBlYmQxNmYxNGMxMDRlZGJmNzY5NzJkMThiBjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMUpIUDJ5Qlh5bXRkSHlhMUpuR1JRMFIzeG52QnY3UW9TSGZ5b3A5MDdqMzg9BjsARkkiGXdhcmRlbi51c2VyLnVzZXIua2V5BjsAVFsISSILUGVyc29uBjsARlsGaUgw--6bbc5ffb34825d01d3802a4a014181ac24540616; __utma=195911998.200911748.1328475493.1335461169.1335468436.11; __utmb=195911998.7.10.1335468436; __utmc=195911998; __utmz=195911998.1328475493.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)</td>
</tr>

<tr>
<td>action_dispatch_cookies:</td>
<td>#<ActionDispatch::Cookies::CookieJar:0x000000042bd438></td>
</tr>

<tr>
<td>action_dispatch_request_unsigned_session_cookie:</td>
<td>{"session_id"=>"e245340ebd16f14c104edbf76972d18b", "_csrf_token"=>"JHP2yBXymtdHya1JnGRQ0R3xnvBv7QoSHfyop907j38=", "warden_user_user_key"=>"[\"Person\", [\"67\"], \"\"]"}</td>
</tr>

<tr>
<td>action_dispatch_request_content_type:</td>
<td>application/x-www-form-urlencoded</td>
</tr>

<tr>
<td>warden:</td>
<td>Warden::Proxy:34985140 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[]}, :intercept_401=>false, :failure_app=>Devise::FailureApp}</td>
</tr>

<tr>
<td>action_dispatch_request_path_parameters:</td>
<td>{"action"=>"keep", "controller"=>"purchases", "id"=>"ms2011-338"}</td>
</tr>

<tr>
<td>action_controller_instance:</td>
<td>#<PurchasesController:0x000000042b64f8></td>
</tr>

<tr>
<td>action_dispatch_request_request_parameters:</td>
<td>{"_method"=>"put", "authenticity_token"=>"JHP2yBXymtdHya1JnGRQ0R3xnvBv7QoSHfyop907j38="}</td>
</tr>

<tr>
<td>action_dispatch_request_parameters:</td>
<td>{"_method"=>"put", "authenticity_token"=>"JHP2yBXymtdHya1JnGRQ0R3xnvBv7QoSHfyop907j38=", "action"=>"keep", "controller"=>"purchases", "id"=>"ms2011-338"}</td>
</tr>

<tr>
<td>action_dispatch_request_formats:</td>
<td>["text/html"]</td>
</tr>

</table>

**Comment by torandi** [comment]
2011...
