### ISSUE TITLE
[production][purchases#pay_multiple] Workflow::NoTransitionAllowed: There is no event pay defined for the edited state

### ISSUE THREAD

**Issue by Frost** [datasektionen/cashflow-old#89]
[See this exception on Errbit](http://errbit.datasektionen.se:80/apps/1c895f4d33680942cb7d15f1fa725081/errs/4fc7c50527314009cb00014f)
# Workflow::NoTransitionAllowed: There is no event pay defined for the edited state
### URL

[http://cashflow.datasektionen.se/inkop/betala](http://cashflow.datasektionen.se/inkop/betala)"
### Where

purchases#pay_multiple
### Occured

May 31  7:22pm
### Similar

4
## Params

```
{
  "_method" => "put",
  "action" => "pay_multiple",
  "authenticity_token" => "fPpEAYDWJaJ5hSdTs0bTE7aBeo+r3qbs6Urv6DthCXw=",
  "commit" => "Save changes",
  "controller" => "purchases",
  "pay" => {
    "49" => "1",
    "72" => "1",
    "79" => "1"
  },
  "utf8" => "â"
}
```
## Session

```
{
  "_csrf_token" => "fPpEAYDWJaJ5hSdTs0bTE7aBeo+r3qbs6Urv6DthCXw=",
  "session_id" => "b3f955f08607de9fcde0d3cb7643d6a6",
  "warden_user_user_key" => "[\"Person\", [\"69\"], \"\"]"
}
```
## Backtrace

```
168:  [GEM_ROOT]/gems/workflow-0.8.1/lib/workflow.rb -> **process_event!**
133:  [GEM_ROOT]/gems/workflow-0.8.1/lib/workflow.rb -> **block (4 levels) in workflow**
118:  /app/controllers/purchases_controller.rb -> **block in pay_multiple**
15:  [GEM_ROOT]/gems/activerecord-3.1.3/lib/active_record/relation.rb -> **each**
15:  [GEM_ROOT]/gems/activerecord-3.1.3/lib/active_record/relation.rb -> **each**
118:  /app/controllers/purchases_controller.rb -> **pay_multiple**
4:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/implicit_render.rb -> **send_action**
167:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/abstract_controller/base.rb -> **process_action**
10:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/rendering.rb -> **process_action**
18:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/abstract_controller/callbacks.rb -> **block in process_action**
452:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/callbacks.rb -> **_run__1846600814466098275__process_action__1167012386479865037__callbacks**
386:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/callbacks.rb -> **_run_process_action_callbacks**
81:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/callbacks.rb -> **run_callbacks**
17:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/abstract_controller/callbacks.rb -> **process_action**
17:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/rescue.rb -> **process_action**
30:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
53:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/notifications.rb -> **block in instrument**
21:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/notifications/instrumenter.rb -> **instrument**
53:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/notifications.rb -> **instrument**
29:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/instrumentation.rb -> **process_action**
201:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/params_wrapper.rb -> **process_action**
18:  [GEM_ROOT]/gems/activerecord-3.1.3/lib/active_record/railties/controller_runtime.rb -> **process_action**
121:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/abstract_controller/base.rb -> **process**
45:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/abstract_controller/rendering.rb -> **process**
193:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal.rb -> **dispatch**
14:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal/rack_delegation.rb -> **dispatch**
236:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_controller/metal.rb -> **block in action**
65:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb -> **call**
65:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb -> **dispatch**
29:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb -> **call**
152:  [GEM_ROOT]/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb -> **block in call**
96:  [GEM_ROOT]/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb -> **block in recognize**
68:  [GEM_ROOT]/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb -> **optimized_each**
95:  [GEM_ROOT]/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb -> **recognize**
141:  [GEM_ROOT]/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb -> **call**
532:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb -> **call**
44:  [GEM_ROOT]/gems/oa-core-0.3.2/lib/omniauth/strategy.rb -> **call!**
30:  [GEM_ROOT]/gems/oa-core-0.3.2/lib/omniauth/strategy.rb -> **call**
35:  [GEM_ROOT]/gems/warden-1.0.6/lib/warden/manager.rb -> **block in call**
34:  [GEM_ROOT]/gems/warden-1.0.6/lib/warden/manager.rb -> **catch**
34:  [GEM_ROOT]/gems/warden-1.0.6/lib/warden/manager.rb -> **call**
17:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/best_standards_support.rb -> **call**
23:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/etag.rb -> **call**
35:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/conditionalget.rb -> **call**
14:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/head.rb -> **call**
21:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/params_parser.rb -> **call**
247:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/flash.rb -> **call**
195:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/session/abstract/id.rb -> **context**
190:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/session/abstract/id.rb -> **call**
331:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/cookies.rb -> **call**
64:  [GEM_ROOT]/gems/activerecord-3.1.3/lib/active_record/query_cache.rb -> **call**
477:  [GEM_ROOT]/gems/activerecord-3.1.3/lib/active_record/connection_adapters/abstract/connection_pool.rb -> **call**
29:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
392:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/callbacks.rb -> **_run_call_callbacks**
81:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/callbacks.rb -> **run_callbacks**
28:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/callbacks.rb -> **call**
101:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/sendfile.rb -> **call**
48:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/remote_ip.rb -> **call**
47:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
13:  [GEM_ROOT]/gems/railties-3.1.3/lib/rails/rack/logger.rb -> **call**
24:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/methodoverride.rb -> **call**
17:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/runtime.rb -> **call**
72:  [GEM_ROOT]/gems/activesupport-3.1.3/lib/active_support/cache/strategy/local_cache.rb -> **call**
15:  [GEM_ROOT]/gems/rack-1.3.6/lib/rack/lock.rb -> **call**
53:  [GEM_ROOT]/gems/actionpack-3.1.3/lib/action_dispatch/middleware/static.rb -> **call**
136:  [GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb -> **forward**
143:  [GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb -> **pass**
155:  [GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb -> **invalidate**
71:  [GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb -> **call!**
51:  [GEM_ROOT]/gems/rack-cache-1.2/lib/rack/cache/context.rb -> **call**
456:  [GEM_ROOT]/gems/railties-3.1.3/lib/rails/engine.rb -> **call**
30:  [GEM_ROOT]/gems/railties-3.1.3/lib/rails/railtie/configurable.rb -> **method_missing**
528:  [GEM_ROOT]/gems/unicorn-4.1.1/lib/unicorn/http_server.rb -> **process_client**
600:  [GEM_ROOT]/gems/unicorn-4.1.1/lib/unicorn/http_server.rb -> **worker_loop**
485:  [GEM_ROOT]/gems/unicorn-4.1.1/lib/unicorn/http_server.rb -> **spawn_missing_workers**
135:  [GEM_ROOT]/gems/unicorn-4.1.1/lib/unicorn/http_server.rb -> **start**
121:  [GEM_ROOT]/gems/unicorn-4.1.1/bin/unicorn -> **<top (required)>**
19:  [GEM_ROOT]/bin/unicorn -> **load**
19:  [GEM_ROOT]/bin/unicorn -> **<main>**

```
## Environment

<table>

<tr>
<td>REMOTE_ADDR:</td>
<td>127.0.0.1</td>
</tr>

<tr>
<td>REQUEST_METHOD:</td>
<td>PUT</td>
</tr>

<tr>
<td>REQUEST_PATH:</td>
<td>/inkop/betala</td>
</tr>

<tr>
<td>PATH_INFO:</td>
<td>/inkop/betala</td>
</tr>

<tr>
<td>REQUEST_URI:</td>
<td>/inkop/betala</td>
</tr>

<tr>
<td>SERVER_PROTOCOL:</td>
<td>HTTP/1.0</td>
</tr>

<tr>
<td>HTTP_VERSION:</td>
<td>HTTP/1.0</td>
</tr>

<tr>
<td>HTTP_HOST:</td>
<td>cashflow.datasektionen.se</td>
</tr>

<tr>
<td>HTTP_X_REAL_IP:</td>
<td>::ffff:109.228.129.45</td>
</tr>

<tr>
<td>HTTP_X_FORWARDED_FOR:</td>
<td>::ffff:109.228.129.45</td>
</tr>

<tr>
<td>HTTP_CONNECTION:</td>
<td>close</td>
</tr>

<tr>
<td>HTTP_USER_AGENT:</td>
<td>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0</td>
</tr>

<tr>
<td>HTTP_ACCEPT:</td>
<td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td>
</tr>

<tr>
<td>HTTP_ACCEPT_LANGUAGE:</td>
<td>sv-se,sv;q=0.8,en-us;q=0.5,en;q=0.3</td>
</tr>

<tr>
<td>HTTP_ACCEPT_ENCODING:</td>
<td>gzip, deflate</td>
</tr>

<tr>
<td>HTTP_DNT:</td>
<td>1</td>
</tr>

<tr>
<td>HTTP_REFERER:</td>
<td>http://cashflow.datasektionen.se/inkop/bekraftade</td>
</tr>

<tr>
<td>HTTP_COOKIE:</td>
<td>__utma=239681174.1061094089.1313865629.1335186397.1336312054.26; __utmz=239681174.1336312054.26.6.utmcsr=facebook.com|utmccn=(referral)|utmcmd=referral|utmcct=/; _cashflow_session=BAh7CEkiD3Nlc3Npb25faWQGOgZFRkkiJWIzZjk1NWYwODYwN2RlOWZjZGUwZDNjYjc2NDNkNmE2BjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMWZQcEVBWURXSmFKNWhTZFRzMGJURTdhQmVvK3IzcWJzNlVydjZEdGhDWHc9BjsARkkiGXdhcmRlbi51c2VyLnVzZXIua2V5BjsAVFsISSILUGVyc29uBjsARlsGaUow--b2e7f3f72a93b39f9dda07fb0bfbc03ba3c1971d; __utma=195911998.615715735.1338491409.1338491409.1338491409.1; __utmb=195911998.19.10.1338491409; __utmc=195911998; __utmz=195911998.1338491409.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)</td>
</tr>

<tr>
<td>CONTENT_TYPE:</td>
<td>application/x-www-form-urlencoded</td>
</tr>

<tr>
<td>CONTENT_LENGTH:</td>
<td>156</td>
</tr>

<tr>
<td>rack_url_scheme:</td>
<td>http</td>
</tr>

<tr>
<td>SERVER_NAME:</td>
<td>cashflow.datasektionen.se</td>
</tr>

<tr>
<td>SERVER_PORT:</td>
<td>80</td>
</tr>

<tr>
<td>key:</td>
<td>action_dispatch.request.query_parameters</td>
</tr>

<tr>
<td>rack_input:</td>
<td>#<Unicorn::TeeInput:0x00000004b80cf0></td>
</tr>

<tr>
<td>rack_errors:</td>
<td>#<File:0x00000000e18750></td>
</tr>

<tr>
<td>rack_multiprocess:</td>
<td>true</td>
</tr>

<tr>
<td>rack_multithread:</td>
<td>false</td>
</tr>

<tr>
<td>rack_run_once:</td>
<td>false</td>
</tr>

<tr>
<td>rack_version:</td>
<td>["1", "1"]</td>
</tr>

<tr>
<td>SERVER_SOFTWARE:</td>
<td>Unicorn 4.1.1</td>
</tr>

<tr>
<td>rack_logger:</td>
<td>#<Logger:0x0000000130c798></td>
</tr>

<tr>
<td>action_dispatch_routes:</td>
<td>#<ActionDispatch::Routing::RouteSet:0x0000000329f588></td>
</tr>

<tr>
<td>action_dispatch_parameter_filter:</td>
<td>["password"]</td>
</tr>

<tr>
<td>action_dispatch_secret_token:</td>
<td>09a55b6ac022b75d133d9111e389542ba7f36b18c71e1eea303e7cf1dc81fa6ee59e5f6d0e7b68770927737c5bf2e8ffc4f43858d381f0e90ef027041ab8ba23</td>
</tr>

<tr>
<td>action_dispatch_show_exceptions:</td>
<td>true</td>
</tr>

<tr>
<td>rack-cache_cache_key:</td>
<td>Rack::Cache::Key</td>
</tr>

<tr>
<td>rack-cache_verbose:</td>
<td>true</td>
</tr>

<tr>
<td>rack-cache_storage:</td>
<td>#<Rack::Cache::Storage:0x00000001ecc038></td>
</tr>

<tr>
<td>rack-cache_metastore:</td>
<td>rails:/</td>
</tr>

<tr>
<td>rack-cache_entitystore:</td>
<td>rails:/</td>
</tr>

<tr>
<td>rack-cache_default_ttl:</td>
<td>0</td>
</tr>

<tr>
<td>rack-cache_ignore_headers:</td>
<td>["Set-Cookie"]</td>
</tr>

<tr>
<td>rack-cache_private_headers:</td>
<td>["Authorization", "Cookie"]</td>
</tr>

<tr>
<td>rack-cache_allow_reload:</td>
<td>false</td>
</tr>

<tr>
<td>rack-cache_allow_revalidate:</td>
<td>false</td>
</tr>

<tr>
<td>rack-cache_use_native_ttl:</td>
<td>false</td>
</tr>

<tr>
<td>rack_request_form_input:</td>
<td>#<Unicorn::TeeInput:0x00000004b80cf0></td>
</tr>

<tr>
<td>rack_request_form_hash:</td>
<td>{"utf8"=>"â", "_method"=>"put", "authenticity_token"=>"fPpEAYDWJaJ5hSdTs0bTE7aBeo+r3qbs6Urv6DthCXw=", "pay"=>{"72"=>"1", "49"=>"1", "79"=>"1"}, "commit"=>"Save changes"}</td>
</tr>

<tr>
<td>rack_methodoverride_original_method:</td>
<td>POST</td>
</tr>

<tr>
<td>action_dispatch_remote_ip:</td>
<td>::ffff:109.228.129.45</td>
</tr>

<tr>
<td>rack_session:</td>
<td>{"session_id"=>"b3f955f08607de9fcde0d3cb7643d6a6", "_csrf_token"=>"fPpEAYDWJaJ5hSdTs0bTE7aBeo+r3qbs6Urv6DthCXw=", "warden_user_user_key"=>"[\"Person\", [\"69\"], \"\"]"}</td>
</tr>

<tr>
<td>rack_session_options:</td>
<td>{"key"=>"expire_after", "path"=>"/", "secure"=>"false", "httponly"=>"true", "defer"=>"false", "renew"=>"false", "coder"=>"#<Rack::Session::Cookie::Base64::Marshal:0x00000003dae668>", "id"=>"b3f955f08607de9fcde0d3cb7643d6a6"}</td>
</tr>

<tr>
<td>rack_request_cookie_hash:</td>
<td>{"__utma"=>"239681174.1061094089.1313865629.1335186397.1336312054.26", "__utmz"=>"239681174.1336312054.26.6.utmcsr=facebook.com|utmccn=(referral)|utmcmd=referral|utmcct=/", "_cashflow_session"=>"BAh7CEkiD3Nlc3Npb25faWQGOgZFRkkiJWIzZjk1NWYwODYwN2RlOWZjZGUwZDNjYjc2NDNkNmE2BjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMWZQcEVBWURXSmFKNWhTZFRzMGJURTdhQmVvK3IzcWJzNlVydjZEdGhDWHc9BjsARkkiGXdhcmRlbi51c2VyLnVzZXIua2V5BjsAVFsISSILUGVyc29uBjsARlsGaUow--b2e7f3f72a93b39f9dda07fb0bfbc03ba3c1971d", "__utmb"=>"195911998.19.10.1338491409", "__utmc"=>"195911998"}</td>
</tr>

<tr>
<td>rack_request_cookie_string:</td>
<td>__utma=239681174.1061094089.1313865629.1335186397.1336312054.26; __utmz=239681174.1336312054.26.6.utmcsr=facebook.com|utmccn=(referral)|utmcmd=referral|utmcct=/; _cashflow_session=BAh7CEkiD3Nlc3Npb25faWQGOgZFRkkiJWIzZjk1NWYwODYwN2RlOWZjZGUwZDNjYjc2NDNkNmE2BjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMWZQcEVBWURXSmFKNWhTZFRzMGJURTdhQmVvK3IzcWJzNlVydjZEdGhDWHc9BjsARkkiGXdhcmRlbi51c2VyLnVzZXIua2V5BjsAVFsISSILUGVyc29uBjsARlsGaUow--b2e7f3f72a93b39f9dda07fb0bfbc03ba3c1971d; __utma=195911998.615715735.1338491409.1338491409.1338491409.1; __utmb=195911998.19.10.1338491409; __utmc=195911998; __utmz=195911998.1338491409.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)</td>
</tr>

<tr>
<td>action_dispatch_cookies:</td>
<td>#<ActionDispatch::Cookies::CookieJar:0x00000004b71ed0></td>
</tr>

<tr>
<td>action_dispatch_request_unsigned_session_cookie:</td>
<td>{"session_id"=>"b3f955f08607de9fcde0d3cb7643d6a6", "_csrf_token"=>"fPpEAYDWJaJ5hSdTs0bTE7aBeo+r3qbs6Urv6DthCXw=", "warden_user_user_key"=>"[\"Person\", [\"69\"], \"\"]"}</td>
</tr>

<tr>
<td>action_dispatch_request_content_type:</td>
<td>application/x-www-form-urlencoded</td>
</tr>

<tr>
<td>warden:</td>
<td>Warden::Proxy:39534560 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[]}, :intercept_401=>false, :failure_app=>Devise::FailureApp}</td>
</tr>

<tr>
<td>action_dispatch_request_path_parameters:</td>
<td>{"action"=>"pay_multiple", "controller"=>"purchases"}</td>
</tr>

<tr>
<td>action_controller_instance:</td>
<td>#<PurchasesController:0x00000004b668f0></td>
</tr>

<tr>
<td>action_dispatch_request_request_parameters:</td>
<td>{"utf8"=>"â", "_method"=>"put", "authenticity_token"=>"fPpEAYDWJaJ5hSdTs0bTE7aBeo+r3qbs6Urv6DthCXw=", "pay"=>{"72"=>"1", "49"=>"1", "79"=>"1"}, "commit"=>"Save changes"}</td>
</tr>

<tr>
<td>action_dispatch_request_parameters:</td>
<td>{"utf8"=>"â", "_method"=>"put", "authenticity_token"=>"fPpEAYDWJaJ5hSdTs0bTE7aBeo+r3qbs6Urv6DthCXw=", "pay"=>{"72"=>"1", "49"=>"1", "79"=>"1"}, "commit"=>"Save changes", "action"=>"pay_multiple", "controller"=>"purchases"}</td>
</tr>

<tr>
<td>action_dispatch_request_formats:</td>
<td>["text/html"]</td>
</tr>

</table>

**Comment by Koronen** [comment]
Vyn '/inkop/bekraftade' är trasig, använd den inte!
