### ISSUE TITLE
budget_posts/show är patetisk

### ISSUE THREAD

**Issue by Frost** [datasektionen/cashflow-old#92]
Den innehåller typ ingen information.

Jag tycker att den åtminstone borde innehålla all info som finns i budget-listan, dvs hur mycket som är budgeterat för innevarande år och hur mycket av det som är använt.

Dessutom skulle man eventuellt kunna lista relaterade inköp...?

**Comment by Koronen** [comment]
Jo, jag håller med dig. Någon får gärna fixa detta.

**Comment by Koronen** [comment]
Nu är den i alla fall inte lika patetisk längre.

**Comment by Frost** [comment]
Ska jag slänga in relaterade inköp också, eller ska vi klassa denna som avslutad?

**Comment by Koronen** [comment]
Nej, jag tycker att det kan räcka såhär så länge. Vissa budgetposter har många inköp, så då riskerar sidan istället att bli för lång.

**Comment by Frost** [comment]
Dåså. Då stänger jag denna.
