### ISSUE TITLE
Inköp med felaktig status

### ISSUE THREAD

**Issue by Frost** [datasektionen/cashflow-old#96]
Det finns en hel del inköp från bland annat mottagningen 2011, som står som bokförda trots att de borde stå som avslutade.

Jag har ingen aning om varför, eller hur det kan ha hänt, men vi behöver göra något åt dem, eftersom de listas bland "bekräftade inköp".

Om man markerar ett utbetalt inköp som bokfört (eller vice versa) ska och kommer det att få status "avslutat". Det verkar inte hänt med dessa inköp.

Jag föreslår att någon sätter sig och går igenom de inköp som listas som bokförda, ser om de även haft "utbetalad" i sin statushistorik, och sen sätter dem till "avslutade" direkt i databasen. 

Kommentarer på detta?

**Comment by torandi** [comment]
Det här beror förmodligen på att jag var tvungen att batchhantera dem
"manuellt", dvs köra rätt action i konsolen, tycker att de borde ha blivit
avslutade dock. Har något svagt minne av att vi hade en bugg kring detta
för ett tag sen.

**Comment by Frost** [comment]
Jo, det är det jag menar... @Koronen satte sig tydligen och pillade runt lite med det strax innan lunch. Den tråkiga biten är ju att man måste dubbelkolla så att de faktiskt varit utbetalda innan man avslutar dem.

**Comment by Frost** [comment]
Ehm... eller mer korrekt: Han verkar ha fixat allihop. Jag stänger denna.

**Comment by Frost** [comment]
Om du satte ett state på dem manuellt, och sparat, kommer de inte avslutas. om du däremot använder `Purchase#keep!` på utbetalda inköp borde de avslutas.

**Comment by torandi** [comment]
Jag har för mig att jag använde keep!

**Comment by Frost** [comment]
Hm... Skumt att det inte funkade isf. Men jaja, vi kanske hade någon bugg i koden då. Det är ju fixat nu iaf, så vi får hoppas att det inte händer igen.
