### ISSUE TITLE
Lägg till roll som är typ treasurer - [godkänna utlägg]

### ISSUE THREAD

**Issue by torandi** [datasektionen/cashflow-old#97]
Det är nice att styrelsen kan gå igenom och klicka bokför på verifikat, men de ska inte kunna godkänna dem.

**Comment by Frost** [comment]
Har du ett förslag på namn på den?

**Comment by Frost** [comment]
bookkeeper kanske?

**Comment by Koronen** [comment]
Låter bra.

**Comment by Frost** [comment]
Vem som nu än fixar detta bör se till att lägga till specs för den nya rollen i ability_spec.

**Comment by Frost** [comment]
Jag har lagt till en roll, med tillhörande testkod i ce41160cef, och deployat till staging, så det är bara att klicka runt där och se om det funkar.
